### ISSUE TITLE
Sending images: images overlap with messageInputBar

### ISSUE THREAD

**Issue by asaplee** [MessageKit/MessageKit#817]
I have gotten sending images to work! However, there remains a problem... When I send the image, for some reason the message input bar overlaps w/ the sent image and it distorts my messageCollectionView. Any ideas for how to fix?
<img width="488" alt="screen shot 2018-08-15 at 12 23 45 am" src="https://user-images.githubusercontent.com/41351290/44136970-9a856b44-a023-11e8-9215-46844dd7d7cd.png">

**Comment by SD10** [comment]
@asaplee I think this bug could be fixed in the upcoming version, MessageKit 1.1.0

**Comment by asaplee** [comment]
Ah- ok. @SD10  any idea when this version will be out?

**Comment by tobitech** [comment]
Please i need this fix too

**Comment by tobitech** [comment]
I found a way to solve this issue by adding these lines of code to my `viewWillAppear` method
`messageCollectionViewBottomInset = keyboardOffsetFrame.height
        `messagesCollectionView.scrollToBottom()``
So whenever another view controller is presented it hides the inputAccessoryView which affects the collectionView bottom inset and isn't restored when the presented view is dismissed. So this was how i fixed it.
Although you don't have to call `messagesCollectionView.scrollToBottom()`

**Comment by justmaaarco** [comment]
Still present on 2.0.0 (it makes totally unusable the image message).

**Comment by nathantannar4** [comment]
@Nem2s are you using any other kind of keyboard manager? Such as `IQKeyboardManager`?

**Comment by justmaaarco** [comment]
> @Nem2s are you using any other kind of keyboard manager? Such as `IQKeyboardManager`?

Nope, followed the basic implementation of the chatViewController. It works great with text messsages but whenever I try to insert an image the messageList is not scrolling anymore and the list is cropped on the bottom.

**Wrapper class**
````
class ChatContainerVC: UIViewController, NavbarDelegate, ChatDelegate {

    let messagesViewController = ChatVC()
    var navBar: NavBarChat!
    var delegate: ImagePickerDelegate!
````

````
override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        if navBar == nil {
            self.navBar = NavBarChat(vc: self, isBackBtnGrey: false, hasRightBtn: true, theFrame: CGRect(
                    x: 0.0,
                    y: 0.0,
                    width: self.view.frame.width,
                    height: NavBar.defaultHeight
            ))
            self.navBar.delegate = self
            self.view.addSubview(self.navBar)
        }
        self.messagesViewController.view.frame = CGRect(x: 0, y: NavBar.defaultHeight, width: view.bounds.width, height: view.bounds.height - NavBar.defaultHeight)
    }
````

**ChatVC**

```
func insertMessage(_ message: Message) {
        DispatchQueue.main.async {
            self.messageList.append(message)
            self.messagesCollectionView.performBatchUpdates({
                self.messagesCollectionView.insertSections([self.messageList.count - 1])
                if self.messageList.count >= 2 {
                    self.messagesCollectionView.reloadSections([self.messageList.count - 2])
                }
            }, completion: { (finished: Bool) in
                if self.isLastSectionVisible() == true {
                    print(self.messagesCollectionView.contentSize.height)
                    self.messagesCollectionView.scrollToBottom(animated: true)
                }
            })
        }
```

**Comment by nathantannar4** [comment]
@Nem2s I see it's a container. Are you adding your ChatVC as a child view controller anywhere? You should see the embedded example I have if your unsure of what I'm speaking of. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by justmaaarco** [comment]
> @Nem2s I see it's a container. Are you adding your ChatVC as a child view controller anywhere? You should see the embedded example I have if your unsure of what I'm speaking of.
> 
> Sent with [GitHawk](http://githawk.com)

Apologise, I forgot to mention those lines:

** ChatContainerVC class**
````
override func viewDidLoad() {
        super.viewDidLoad()
        /// Add the `ConversationViewController` as a child view controller
        messagesViewController.willMove(toParent: self)
        self.addChild(messagesViewController)
        view.addSubview(messagesViewController.view)
        messagesViewController.didMove(toParent: self)
        messagesViewController.delegate = self
        messagesViewController.parentVC = self

    }
````
```
//Required for the `MessageInputBar` to be visible
    override var canBecomeFirstResponder: Bool {
        return messagesViewController.canBecomeFirstResponder && !isImagePickerShowed
    }

    //Required for the `MessageInputBar` to be visible
    override var inputAccessoryView: UIView? {
        if !isImagePickerShowed {
            return messagesViewController.inputAccessoryView
        } else {
            return nil
        }
    }
```

Is there something wrong with the configuration of the child viewController?

**Comment by nathantannar4** [comment]
Ok, I thought this was fixed but I'll take another look using only image messages. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nathantannar4** [comment]
@Nem2s are you using 2.0? I cannot reproduce this in the example. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nathantannar4** [comment]
How are you setting the frame of the chat VC?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by justmaaarco** [comment]
> How are you setting the frame of the chat VC?
> 
> Sent with [GitHawk](http://githawk.com)

Sorry for the late reply I have been off for few days. Anyway this is the code to set the frame of the viewController:
````
override func viewDidLoad() {
        super.viewDidLoad()
       ...
        self.messagesViewController.view.frame = CGRect(x: 0, y: NavBar.defaultHeight, width: view.bounds.width, height: view.bounds.height - NavBar.defaultHeight)
    }
````

where `messageViewController` is instance of `ChatVC`

**Comment by justmaaarco** [comment]
> @Nem2s are you using 2.0? I cannot reproduce this in the example.
> 
> Sent with [GitHawk](http://githawk.com)

Yes sir, I'm using the latest version from Cocoapods.
It's really weird because the bubble is scrolled correctly with text but when i put an image it scrolls down but the bottom margin is not set on top of the inputbar but on top of the scrollview behind. Like in the image below: 

<a href="https://imgbb.com/"><img src="https://i.ibb.co/TMB958z/Screenshot-2018-12-18-at-09-40-32.png" alt="Screenshot-2018-12-18-at-09-40-32" border="0"></a>

**Comment by justmaaarco** [comment]
@nathantannar4 is there any news about that?

**Comment by nathantannar4** [comment]
@Nem2s I have no way of really debugging this for you. I ran the example with only images and did not have this problem.

I suspect it has something to do with the way your laying out the VC as a child VC. Look at the example project I have for the embedded example. Make sure your not adjusting the top/bottom inset of the MessagesCollectionView as well. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by victors1681** [comment]
I was running into the same issue, so I noticed this bug is related when I presented a new controller to pick an image after dismiss the pick Image view the layout and keyboard event broke, I used present as Modally and is working for me,

 `

          picker.modalPresentationStyle = UIModalPresentationStyle.overCurrentContext
          picker.modalTransitionStyle = UIModalTransitionStyle.crossDissolve

          self.present(picker, animated: true, completion: nil)
        
         //hide the input  and after pick the image make the input visible 
         self.messageInputBar.isHidden = true

`
